language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - build-tools-25.0.0
    - android-25
    - extra

notifications:
  email: false

sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

licenses:
  - android-sdk-license-.+
  - '.+'

script:
  - ./gradlew build assembleAndroidTest

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\ne6b7c2ab7fa2298c15165e9583d0acf0b04a2232" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"

after_success:
  - ./gradlew createRegularMinSdkDebugCoverageReport
  - pip install --user codecov
  - codecovg
